kubeval resources/CertificateSigningRequest.yaml &&
kubeval resources/ClusterRole.yaml &&
kubeval resources/ClusterRoleBinding.yaml &&
kubeval resources/ConfigMap.yaml &&
kubeval resources/CronJob.yaml &&
#kubeval resources/CustomResourceDefinition.yaml &&
kubeval resources/DaemonSet.yaml &&
kubeval resources/Deployment.yaml &&
kubeval resources/EndpointSlice.yaml &&
kubeval resources/Endpoints.yaml &&
kubeval resources/HorizontalPodAutoscaler.yaml &&
kubeval resources/Ingress.yaml &&
kubeval resources/IngressClass.yaml &&
kubeval resources/Job.yaml &&
kubeval resources/LimitRange.yaml &&
kubeval resources/List.yaml &&
kubeval resources/MutatingWebhookConfiguration.yaml &&
kubeval resources/Namespace.yaml &&
kubeval resources/NetworkPolicy.yaml &&
kubeval resources/Node.yaml &&
kubeval resources/PersistentVolume.yaml &&
kubeval resources/PersistentVolumeClaim.yaml &&
kubeval resources/Pod.yaml &&
kubeval resources/PodDisruptionBudget.yaml &&
kubeval resources/PodSecurityPolicy.yaml &&
kubeval resources/PriorityClass.yaml &&
kubeval resources/ReplicaSet.yaml &&
kubeval resources/ReplicationController.yaml &&
kubeval resources/ResourceQuota.yaml &&
kubeval resources/Role.yaml &&
kubeval resources/RoleBinding.yaml &&
kubeval resources/RuntimeClass.yaml &&
kubeval resources/Secret.yaml &&
kubeval resources/Service.yaml &&
kubeval resources/ServiceAccount.yaml &&
kubeval resources/StatefulSet.yaml &&
kubeval resources/StorageClass.yaml &&
kubeval resources/ValidatingWebhookConfiguration.yaml